# Generated by Django 4.2.2 on 2023-06-15 08:18

import app_channel.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=255, verbose_name='название канала')),
                ('full_name', models.CharField(max_length=255, verbose_name='имя')),
                ('description', models.TextField(verbose_name='описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='активный канал')),
                ('avatar', models.ImageField(upload_to=app_channel.models.path_for_avatar_channel, verbose_name='аватарка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания канала')),
                ('keywords', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='владелец канала')),
                ('subscribers', models.ManyToManyField(related_name='subscribers', to=settings.AUTH_USER_MODEL, verbose_name='подписчики')),
            ],
            options={
                'verbose_name': 'канал',
                'verbose_name_plural': 'каналы',
            },
        ),
    ]
