# Generated by Django 4.2.2 on 2023-06-14 12:04

import app_main.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название видео')),
                ('description', models.TextField(verbose_name='описание')),
                ('video', models.FileField(upload_to=app_main.models.path_for_video, verbose_name='видео')),
                ('image', models.ImageField(upload_to=app_main.models.path_for_video, verbose_name='картинка видео')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visibility', models.CharField(choices=[('public', 'открытый доступ'), ('private', 'приватный доступ'), ('unlisted', 'закрытый доступ'), ('member_only', 'только подписчикам')], default='public', max_length=20, verbose_name='доступ')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='просмотры')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'видео',
                'verbose_name_plural': 'видео',
            },
        ),
    ]
